version: '3'

services:
  app:
    image: kumpapan/strapi
    container_name: 67-ced-strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=192.168.211.189
      - DATABASE_PORT=54321
      - DATABASE_NAME=kumpapan
      - DATABASE_USERNAME=kumpapan
      - DATABASE_PASSWORD=P-Tr823i7L

